/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wochacha_learnjni_utils_JNIUtils */

#ifndef _Included_com_wochacha_learnjni_utils_JNIUtils
#define _Included_com_wochacha_learnjni_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wochacha_learnjni_utils_JNIUtils
 * Method:    helloFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wochacha_learnjni_utils_JNIUtils_helloFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_wochacha_learnjni_utils_JNIUtils
 * Method:    Add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wochacha_learnjni_utils_JNIUtils_Add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
